dist: xenial
language: bash
env:
  global:
    secure: lDfqWMQVHM3TE1HAPAVwmPE2Oa3CDJfajPtjWu0dnKM3TV1MnmuOqJtADP07Cb8dy1kMmLUt7SIngHHaXB/gS/cXEEDnXJr5gUK7tS8IuyTB7f1vZ7NmHEHRC4gggfCisHR4M0ZuzOTctdZXrg7xEhaRqtxUSS5OyaaMkM+rtHvO8/ZZiG2re9w4mf4279JSHifmESXlGCgZFnkn6fkthdZfGigxUggtBQFzUIrcrX9iWol2jYuCG38rYAaLPBKoP+GyAvSJvKFikU+PA6F7NHaSmaq1flObD5wPf7rKBJsnpG1tSZ7+058jPgyn5WW/8XV9m9zRRJ0smBnHasyxchzPG7oiuOQTJY0MNuAc6BaOAEiYi4/Y3kFoWtmSFjF2xVRus1lyPAARp1ClmmVKREYNlcMPsf6TQwBOmxk29V5s6EWxQgVZiptwh7baQAFgXqz+dlHhdYIj47oPAPoVV8dq5ucoTDUmzcrqdE1AK8O03dnyyCKRwTQRk81M9ZO2RYLkIjljLpPgq3BFfj3lDl/kV3fAPECnfIL7QjLwQP2d9rEsJVS8m6FfXwGcCWwyaOpZFniyQNyFFt7JFRHz5WVIbvatsti6xnVpTewqsTsNJZDvOsdDceSE46lNQEjhBnBiIBqtHuHsR638BjApauUmGbRt8K6PE2L1mUk25qY=
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bash
after_script:
- ".github/notification.sh"
notifications:
  email: false
  slack:
    secure: WqIeI72avnqvXXwYRaO/TuTl0Mzwyy/3pUqy7in2E+75LhcrSLHzyFmz2QoIkCLv5h9vA7zLmhv6d5Chy+GAF9QKvZqMQI6i2fqs4lNVA+cgNR88kdSXHfUNXH8tJhAJHW3jxL19SViQE+e0vMy/YhlNdzVNZYz4FJGWpqRDGwmj14iSvbegxfDPoIwlq+xr3pDbjXQ5asVLuSxPakJPsx+es+kwag28+54LliNUaX+TTr2U2RgTDx1A+pT9glCNqcQTx6h5mrfBh5b7ArwndZtPvjzIcWq7VxwlD945FrvxN4Ec0+GgVSuJDIezPwU1Jl4/q0dlJX1QyyCaT17XcOmbAsB1ZYN7XQt9xQzPGhQjLwx9DSLu1yikOxBvcHR8s/L1agZi3XrnJReQ+laDuAsVdDEMdEC3QvJbA4gY+p3mQeuILZvzMCbik1UE/STtaXOAG+skg7ttcLK+J3P7C7WmrI+k2gmw1s6XD0YmjTVTraksTulYObo/0kzHQxapGkonK70CbEBwkqNJPGcsi4IBRi8F3hzuxqlm1D/PYZRotft6bWtldDcSSfF72+ymhLWRAbck00GoV5oO6L8xRSUu0YE3J/rsPuv+HyQiQhVfD4GDN0wdJVsSCEgi9tXkiu/gqzWgn5YgQit7WeX4vqFYugQ1q10ZqrBRkRXq0qA=
    on_success: always
    on_failure: always
